server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:eagle;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org.springframework: INFO
    com.eagle: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    persistAuthorization: true
  api-docs:
    enabled: true
    path: /v3/api-docs
